"""Add job_title_category to contacts

Revision ID: 8be6196bd921
Revises: 6e2a6b9f836d
Create Date: 2026-02-27 18:18:21.722359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be6196bd921'
down_revision: Union[str, Sequence[str], None] = '6e2a6b9f836d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('job_title_category', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'job_title_category')
    # ### end Alembic commands ###
