"""add entry_type to Entry

Revision ID: 8e754ea97687
Revises: a836564f929d
Create Date: 2026-03-21 04:58:37.722045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e754ea97687'
down_revision: Union[str, Sequence[str], None] = 'a836564f929d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('entry_type', sa.String(), server_default='NOTE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'entry_type')
    # ### end Alembic commands ###
