"""add_meeting_chunk

Revision ID: a836564f929d
Revises: 431ebb03799e
Create Date: 2026-03-20 13:33:23.278310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a836564f929d'
down_revision: Union[str, Sequence[str], None] = '431ebb03799e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_chunks_session_id'), 'meeting_chunks', ['session_id'], unique=False)
    op.create_index(op.f('ix_meeting_chunks_user_id'), 'meeting_chunks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_chunks_user_id'), table_name='meeting_chunks')
    op.drop_index(op.f('ix_meeting_chunks_session_id'), table_name='meeting_chunks')
    op.drop_table('meeting_chunks')
    # ### end Alembic commands ###
